version: '3.8'

services:
  db:
    image: postgres:14
    container_name: catalog-db
    environment:
      - POSTGRES_USER=catalog_user
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=catalog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - catalog-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalog_user -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SQLALCHEMY_DATABASE_URI=postgresql://catalog_user:admin1234@db:5432/catalog_db
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - catalog-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: catalog-frontend
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - catalog-network

networks:
  catalog-network:
    driver: bridge

volumes:
  postgres_data: